package coffee.michel.usermanager.api

/**
 * This data class is a projection of the data this services receives from the user.
 * It does not contain data which will be generated by the service.
 */
@kotlinx.serialization.Serializable
internal data class SubjectWriteDto(
    val username: String,
    val password: String
) {

    override fun toString(): String {
        return "SubjectWriteDto(username='$username', password='<hidden>')"
    }
}
